apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-9
  description: Python app that displays time - named python-9
  annotations:
    github.com/project-slug: LuC-9/python-9
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: development
  lifecycle: experimental
